config/routes.rb
Whatthejug::Application.routes.draw do
  devise_for :admins

  resources :images

  match "info" => "static#info", :as => "info"
  match "tags" => "images#tag_cloud", :as => "tag_cloud"
  match "search" => "images#search", :as => "search"
  match "random" => "images#random", :as => "random"
  match "review" => "images#review", :as => "review"

  root :to => "images#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :unreviewed, :url, :tags, :source

  attr_accessible :data

  before_create :set_default_values

  has_attached_file :data,
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename"

  acts_as_taggable

  def set_default_values
    self.unreviewed ||= true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  before_filter :authenticate_admin!, :only => [:review]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all :conditions => { :unreviewed => false }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /random
  # GET /random.json

  def random
    @images = Image.where(unreviewed: false).order("RANDOM()")

    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    params[:images].each do |image|
      @image = Image.new(image)
      @image.save
    end

    respond_to do |format|
      @images = Image.where(unreviewed: false).all
      format.html { render action: "index" }
    end

  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    tags = params[:image].delete :tags

    @image.tag_list = tags

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  # GET /images/tag_cloud
  def tag_cloud
    @tags = Image.tag_counts
  end

  # GET /search?query=tags

  def search
    query = params[:query]
    @images = Image.tagged_with(query.split(","))

    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @images }
    end

  end

  def review
    @images = Image.where(:unreviewed => true).all

    respond_to do |format|
      format.html { render "index" }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_display_images.html.erb
<% @images.each do |image| %>
  <div class="box">
    <% if session[:admin] %>
      <%= link_to image_tag(image.data.url), edit_image_path(image) %>
    <% else %>
      <%= link_to image_tag(image.data.url), image %>
    <% end %>
  </div>
<% end %>


<script>
  WTJ.Images.layoutImages($("#imagesContainer"));
</script>

app/views/images/_form.html.erb
<%= form_tag "/images", :multipart => true do %>
  <%= file_field_tag "images", :multiple => true, :name => "images[][data]" %>
  <br>
  <%= submit_tag "Submit", :class => "btn" %>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= form_for @image do |f| %>
  <div class="field">
    <%= f.label :tags %></br> 
    <%= f.text_field :tags, :value => "#{@image.tag_list.join(",")}", :placeholder => "finn,jake,awesome" %>
    <%= f.label :source %></br>
    <%= f.text_field :source, :value => "#{@image.source}", :placeholder => "http://www.imgur.com" %>
  </div>

  <% if admin_signed_in? %>
    <%= f.label :unreviewed %></br>
    <%= f.check_box :unreviewed %>
  <% end %>

  <div class="actions">
    <%= f.submit :class => "btn" %>
  </div>
<% end %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<%= render "display_images" %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<p>Your image will be reviewed, so don't panic if you don't see it right away.</p>

app/views/images/show.html.erb
<div id="imagesWrapper">
  <div>
    <img src="<%= @image.url %>">
  </div>

  <%= image_tag @image.data.url %>

  <div class="imageMenu">
    Tags: 

    <% @image.tags.each do |tag| %>
      <%= tag.name %>
  <% end %>
  <br>

    <%= link_to 'Edit', edit_image_path(@image) %> |
    <%= link_to 'Back', images_path %>
  </div>
</div>

app/views/images/tag_cloud.html.erb
<% @tags.each do |tag| %>
  <p>
  <%= link_to "#{tag.name} (#{tag.count})", search_path(:query => tag.name) %>
  </p>
<% end %>

app/views/layouts/_toolbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "What the Jug", root_path, :class => "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li id="homebtn"><%= link_to "Home", root_path %></li>
          <li id="submitbtn"><%= link_to "Submit", new_image_path %></li>
          <li id="randombtn"><%= link_to "Random", random_path %></li>
          <li id="tagsbtn"><%= link_to "Tags", tag_cloud_path %></li>
          <li id="infobtn"><%= link_to "Info", info_path %></li>
          <% if admin_signed_in? %>
            <li><%= link_to 'Sign out', destroy_admin_session_path, :method => "delete" %></li>
          <% end %>
        </ul>
      </div>
      <%= form_tag "/search", :class => "navbar-search pull-left" do %>
        <%= text_field_tag :query, nil, :class => "search-query", :placeholder => "finn,awesome,scary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What the Jug?</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/toolbar" %>


<div id="imagesWrapper">
  <div id="imagesContainer">
    <%= yield %>
  </div>
</div>
</body>
</html>